version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - cd ../angular-app
      - npm install
      - npm run test
      - npm run build

artifacts:
  files:
    - angular-app/dist/angular-app/*
  name: webapp
  discard-paths: yes
