version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 12
  pre_build:
    commands:
      - rm -rf angular-app/dist
  build:
    commands:
      - echo 'hi'
      - cd angular-app
      - npm install
      - npm run blowup
      - npm run build
    finally:
      - echo 'whether I finished right or not here I am'
      - echo ${?}
  post_build:
    commands:
      - echo 'build status'
      - echo ${?}
reports:
  junitreports:
    files:
      - backend/build/test-results/test/*.xml

artifacts:
  files:
    - angular-app/dist/angular-app/**