AWSTemplateFormatVersion:                           "2010-09-09"
Description:                                        "Self hosted AWS application"

# Directly lifted from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-s3.html
# we're just creating an S3 bucket and using it to host a website written in Angular
Resources:
   ShoppingListTable:
     Type: AWS::DynamoDB::Table
     Properties:
       AttributeDefinitions:
         - AttributeName: "OwnerId"
           AttributeType: "S"
         - AttributeName: "ItemId"
           AttributeType: "S"
       TableName: !Sub "${AWS::StackName}ShoppingList"
       KeySchema:
         - AttributeName: "OwnerId"
           KeyType: "HASH"
         - AttributeName: "ItemId"
           KeyType: "RANGE"
       ProvisionedThroughput:
         ReadCapacityUnits: 2
         WriteCapacityUnits: 2
Outputs:
  TableArn:
    Value:                      !GetAtt "ShoppingListTable.Arn"
